---
title: "Employee Turnover"
author: "Joshua Zhong"
date: "04/24/2024"
output:
 html_document:
  toc: yes
  toc_depth: 4
  toc_float: yes
  fig_width: 6
  fig_caption: yes
  number_sections: yes
  theme: readable
  editor_options:
  chunk_output_type: console
---




```{=html}

<style type="text/css">

/* Cascading Style Sheets (CSS) is a stylesheet language used to describe the presentation of a document written in HTML or XML. it is a simple mechanism for adding style (e.g., fonts, colors, spacing) to Web documents. */

h1.title {  /* Title - font specifications of the report title */
  font-size: 24px;
  color: DarkRed;
  text-align: center;
  font-family: "Gill Sans", sans-serif;
}
h4.author { /* Header 4 - font specifications for authors  */
  font-size: 20px;
  font-family: system-ui;
  color: DarkRed;
  text-align: center;
}
h4.date { /* Header 4 - font specifications for the date  */
  font-size: 18px;
  font-family: system-ui;
  color: DarkBlue;
  text-align: center;
}
h1 { /* Header 1 - font specifications for level 1 section title  */
    font-size: 22px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
}
h2 { /* Header 2 - font specifications for level 2 section title */
    font-size: 20px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
}

h3 { /* Header 3 - font specifications of level 3 section title  */
    font-size: 18px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
}

h4 { /* Header 4 - font specifications of level 4 section title  */
    font-size: 18px;
    font-family: "Times New Roman", Times, serif;
    color: darkred;
    text-align: left;
}

body { background-color:white; }

.highlightme { background-color:yellow; }

p { background-color:white; }

</style>
```


```{r options, echo = FALSE, include = FALSE}

options(scipen = 2)


   library(tidyverse)
   library(GPArotation)
   library(psych)
   library(nFactors)
   library(rmarkdown)
   library(knitr)
   library(parameters)
   library(corrplot)
   library(ggcorrplot)
   library(ggfortify)
   library(dplyr)
   require(ggplot2)
   require(GGally) 
   require(CCA)
   require(olsrr)
   require(cocron)

   library(psych)



# Specifications of outputs of code in code chunks
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	comment = FALSE,
	results = TRUE, 
	digits = 4
)


```


```{r import data}

turnover_data <- read.csv("https://raw.githubusercontent.com/JZhong01/STA490/main/Week15/turnover-data-set.csv")


```


```{r data preprocessing}

turnover_data2 <- turnover_data

turnover_data2$gender <- ifelse(turnover_data2$gender == "m", 1, 0)
#male = 1, female = 0

turnover_data2$greywage <- ifelse(turnover_data2$greywage == "grey", 1, 0) #grey = 1, white = 0

turnover_data2$head_gender <- ifelse(turnover_data2$head_gender == "m", 1, 0)
#male = 1, female = 0

turnover_data2 <- turnover_data2 %>%
  mutate(way = case_when(
    way == "foot" ~ 0,
    way == "bus"  ~ 1,
    way == "car"  ~ 2
  ))
#by foot = 0, by bus = 1, by car = 2

turnover_data2 <- turnover_data2 %>%
  mutate(coach = case_when(
    coach == "no" ~ 0,
    coach == "yes"  ~ 1,
    coach == "my head"  ~ 2
  ))
#no coach = 0, non-boss coach = 1, boss was coach = 2


turnover_data2 <- turnover_data2 %>%
  mutate(industry = case_when(
      industry %in% c("Banks", "RealEstate", "Insurance") ~ 1,
      industry %in% c("manufacture", "Building", "PowerGeneration") ~ 2,
      industry %in% c("Retail", "HoReCa", "Telecom") ~ 3,
      industry %in% c("IT", "Consult", "Telecom") ~ 4,
      TRUE ~ 5
  )) 
#Grouped into 5 aggregate industries: Finance (1), Industrial (2), Commercial (3), Tech (4), Other (5)

turnover_data2 <- turnover_data2 %>%
  mutate(profession = case_when(
    profession %in% c("Accounting", "Finan?e", "Law") ~ 1,
    profession %in% c("Sales", "Marketing", "BusinessDevelopment", "Commercial") ~ 2,
    profession %in% c("HR", "PR") ~ 3,
    profession %in% c("Engineer", "IT", "Consult") ~ 4,
    profession %in% c("Teaching", "manage") ~ 5,
    profession == "etc" ~ 0
))

#Grouped into 6 aggregate professions: Finance/Legal (1), Sales/Marketing (2), Human/Public Relations (3), Technical (4), Education & Management (5), Other (0) 


turnover_data2 <- turnover_data2 %>%
  rename(Agreeableness = independ, Extraversion = extraversion, Conscientiousness = selfcontrol, Neuroticism = anxiety, Openness = novator)
#Rename Big 5 Personalities 



turnover_data2 <-turnover_data2 %>%
  mutate(traffic = case_when(
    traffic %in% c("KA", "advert", "recNErab", "referal", "youjs")~ 1,
    traffic %in% c("empjs", "friends", "rabrecNErab") ~ 0
     )
)
# You initiate reaching out to employer ~ 1, Employer reaches out to you ~ 0

   
   
   
```



```{r EDA}

hist(turnover_data2$age)

sum(is.na(turnover_data2)) # 0 NA values


pairs.panels(turnover_data2, pch=21, main="Pair-wise Scatter Plot of r numerical variables")

#describe(turnover_data2)

par(mfrow= c(2,2))

hist(turnover_data2$stag, xlab = "Experience", main = "Histogram of Relevant Experience")
hist(turnover_data2$age, xlab = "Age", main = "Histogram of Employee Ages")
hist(turnover_data2$Extraversion, xlab = "Score", main = "Histogram of Extraversion Scores")
hist(turnover_data2$Agreeableness, xlab = "Score", main = "Histogram of Agreeableness Scores")
hist(turnover_data2$Conscientiousness, xlab = "Score", main = "Histogram of Conscientiousness Scores")
hist(turnover_data2$Neuroticism, xlab = "Score", main = "Histogram of Neuroticism Scores")
hist(turnover_data2$Openness, xlab = "Score", main = "Histogram of Openness Scores")

```

